services:
  - type: web
    name: zeril-bot
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: HF_TOKEN
        value: YOUR_HUGGINGFACE_API_TOKEN
    healthCheckPath: /health
    autoDeploy: yes
