services:
  - type: web
    name: zeril-bot
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_ACTUAL_TOKEN
      - key: HF_TOKEN
        value: YOUR_ACTUAL_HF_TOKEN
    dockerCommand: "python main.py"
    healthCheckPath: /health
