services:
  - type: web
    name: zeril-telegram-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: BOT_TOKEN
        value: 8048986424:AAE37IBwkCzE5oKtGCdN-mnnsMrcrlzGWUQ
      - key: HF_API_KEY
        value: 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
      - key: PORT
        value: 8080
    healthCheckPath: /
